<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CourseUnit;
use App\Models\Level;
use App\Models\Program;

class CourseUnitSeeder extends Seeder
{
    public function run(): void
    {
        $licInfo = Program::where('code', 'LIC-INFO')->first();
        $l1 = Level::where('code', 'L1')->where('program_id', $licInfo->id)->first();
        $l2 = Level::where('code', 'L2')->where('program_id', $licInfo->id)->first();
        $l3 = Level::where('code', 'L3')->where('program_id', $licInfo->id)->first();

        // UE L1 S1
        $courseUnits = [
            // L1 - Semestre 1
            [
                'code' => 'INF101',
                'name' => 'Introduction à l\'Informatique',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 3,
                'hours_cm' => 30,
                'hours_td' => 20,
                'hours_tp' => 10,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF102',
                'name' => 'Algorithmique et Programmation',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 30,
                'hours_td' => 20,
                'hours_tp' => 20,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'MAT101',
                'name' => 'Mathématiques Discrètes',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 4,
                'coefficient' => 2,
                'hours_cm' => 24,
                'hours_td' => 16,
                'hours_tp' => 0,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'ENG101',
                'name' => 'English for Computer Science',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 3,
                'coefficient' => 1,
                'hours_cm' => 20,
                'hours_td' => 10,
                'hours_tp' => 0,
                'ue_type' => 'TRANSVERSAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.5,
                'exam_weight' => 0.5,
            ],
            // L1 - Semestre 2
            [
                'code' => 'INF103',
                'name' => 'Bases de Données',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 3,
                'hours_cm' => 30,
                'hours_td' => 15,
                'hours_tp' => 15,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF104',
                'name' => 'Architecture des Ordinateurs',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 3,
                'hours_cm' => 28,
                'hours_td' => 18,
                'hours_tp' => 10,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'MAT102',
                'name' => 'Algèbre Linéaire',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 4,
                'coefficient' => 2,
                'hours_cm' => 26,
                'hours_td' => 14,
                'hours_tp' => 0,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'FRA101',
                'name' => 'Français Technique',
                'level_id' => $l1->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 3,
                'coefficient' => 1,
                'hours_cm' => 18,
                'hours_td' => 12,
                'hours_tp' => 0,
                'ue_type' => 'TRANSVERSAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.5,
                'exam_weight' => 0.5,
            ],
            // L2 - Semestre 1
            [
                'code' => 'INF201',
                'name' => 'Programmation Orientée Objet',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 30,
                'hours_td' => 20,
                'hours_tp' => 20,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF202',
                'name' => 'Systèmes d\'Exploitation',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 3,
                'hours_cm' => 28,
                'hours_td' => 16,
                'hours_tp' => 16,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF203',
                'name' => 'Réseaux Informatiques',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 5,
                'coefficient' => 3,
                'hours_cm' => 26,
                'hours_td' => 14,
                'hours_tp' => 12,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'MAT201',
                'name' => 'Probabilités et Statistiques',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 4,
                'coefficient' => 2,
                'hours_cm' => 24,
                'hours_td' => 16,
                'hours_tp' => 0,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            // L2 - Semestre 2
            [
                'code' => 'INF204',
                'name' => 'Génie Logiciel',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 32,
                'hours_td' => 18,
                'hours_tp' => 16,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF205',
                'name' => 'Programmation Web',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 3,
                'hours_cm' => 26,
                'hours_td' => 14,
                'hours_tp' => 20,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF206',
                'name' => 'Sécurité Informatique',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 4,
                'coefficient' => 2,
                'hours_cm' => 20,
                'hours_td' => 12,
                'hours_tp' => 8,
                'ue_type' => 'FUNDAMENTAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'ENG201',
                'name' => 'Professional English',
                'level_id' => $l2->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 3,
                'coefficient' => 1,
                'hours_cm' => 18,
                'hours_td' => 12,
                'hours_tp' => 0,
                'ue_type' => 'TRANSVERSAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.5,
                'exam_weight' => 0.5,
            ],
            // L3 - Semestre 1
            [
                'code' => 'INF301',
                'name' => 'Intelligence Artificielle',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 32,
                'hours_td' => 18,
                'hours_tp' => 16,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF302',
                'name' => 'Machine Learning',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 30,
                'hours_td' => 16,
                'hours_tp' => 20,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF303',
                'name' => 'Cloud Computing',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 5,
                'coefficient' => 3,
                'hours_cm' => 28,
                'hours_td' => 12,
                'hours_tp' => 16,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF304',
                'name' => 'Projet de Fin d\'Études I',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 1,
                'credits' => 5,
                'coefficient' => 2,
                'hours_cm' => 0,
                'hours_td' => 0,
                'hours_tp' => 40,
                'ue_type' => 'OPTIONAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.5,
                'exam_weight' => 0.5,
            ],
            // L3 - Semestre 2
            [
                'code' => 'INF305',
                'name' => 'Cybersécurité Avancée',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 30,
                'hours_td' => 16,
                'hours_tp' => 16,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF306',
                'name' => 'Big Data Analytics',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 6,
                'coefficient' => 4,
                'hours_cm' => 28,
                'hours_td' => 14,
                'hours_tp' => 18,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF307',
                'name' => 'DevOps et Déploiement',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 5,
                'coefficient' => 3,
                'hours_cm' => 24,
                'hours_td' => 10,
                'hours_tp' => 18,
                'ue_type' => 'METHODOLOGY',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.4,
                'exam_weight' => 0.6,
            ],
            [
                'code' => 'INF308',
                'name' => 'Projet de Fin d\'Études II',
                'level_id' => $l3->id,
                'program_id' => $licInfo->id,
                'semester_number' => 2,
                'credits' => 8,
                'coefficient' => 3,
                'hours_cm' => 0,
                'hours_td' => 0,
                'hours_tp' => 50,
                'ue_type' => 'OPTIONAL',
                'regime' => 'MANDATORY',
                'cc_weight' => 0.3,
                'exam_weight' => 0.7,
            ],
        ];

        foreach ($courseUnits as $cu) {
            CourseUnit::updateOrCreate(
                ['code' => $cu['code']],
                $cu
            );
        }
    }
}

